// <auto-generated />
using System;
using Infrastructure.Database.MySQLDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MySqlDatabase))]
    [Migration("20231227150732_AddededDomain")]
    partial class AddededDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanFly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdb1d7e6-d869-4dcf-835b-5042886d860b"),
                            CanFly = false,
                            Name = "Parrot",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2e37c193-0be7-46cc-913e-dd80d004c469"),
                            CanFly = false,
                            Name = "Cortex",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("fe5303f8-d3ff-44c9-935b-eecdae483a88"),
                            CanFly = false,
                            Name = "Fench",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1ecf60ce-c9d3-4505-8df4-1416a874daab"),
                            CanFly = false,
                            Name = "Feri",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Domain.Models.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69f28847-84bf-427c-8199-1e63f07a250f"),
                            LikesToPlay = false,
                            Name = "Nuno",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("8ac9cd5c-2454-4834-a0e0-081184a1935e"),
                            LikesToPlay = false,
                            Name = "Mani",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("116ef989-e16a-460e-bb63-0528bfabbe8b"),
                            LikesToPlay = false,
                            Name = "Puppy",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("eceeee5f-7054-4d2b-b077-8f6666b691f2"),
                            LikesToPlay = false,
                            Name = "Shima",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("5eb58d12-144e-4d1c-a20d-b3dca8e5524f"),
                            LikesToPlay = false,
                            Name = "Sedel",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("479277f3-429f-40a5-a77b-ae01aa322e9c"),
                            LikesToPlay = false,
                            Name = "Tom",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("9e1b657e-72c7-4d55-bbe0-d5974ffef53f"),
                            LikesToPlay = false,
                            Name = "Misha",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("9f832ab5-1c88-4804-8183-c332a5331ae1"),
                            LikesToPlay = false,
                            Name = "Tezar",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        });
                });

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
