// <auto-generated />
using System;
using Infrastructure.Database.MySQLDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MySqlDatabase))]
    [Migration("20231227151327_ChnagesToDogs")]
    partial class ChnagesToDogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanFly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8165403-9d59-44ae-81ab-249b9f4eb832"),
                            CanFly = false,
                            Name = "Parrot",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("29b86f54-42b4-47c6-aeaa-8de784fdfdcb"),
                            CanFly = false,
                            Name = "Cortex",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("207f4c9a-ef02-46c5-a058-6d26bb4d13b5"),
                            CanFly = false,
                            Name = "Fench",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7935d9f0-eb29-4557-a608-cc5bc032c2eb"),
                            CanFly = false,
                            Name = "Feri",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Domain.Models.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77776dc3-bf00-4f35-9310-d098a200b9c7"),
                            LikesToPlay = false,
                            Name = "Nuno",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("6c5d68e9-a87c-4539-a125-f1835015b3f5"),
                            LikesToPlay = false,
                            Name = "Mani",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("8b7ecdcc-5bcb-4174-9d75-367dde75037d"),
                            LikesToPlay = false,
                            Name = "Puppy",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("97bf165f-4675-43d1-b6d7-b1033c0d2784"),
                            LikesToPlay = false,
                            Name = "Shima",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        });
                });

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8426c09a-321d-4098-b695-a495fa22ddee"),
                            Name = "Sedel",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("2df3b91c-5392-4c23-a0b6-5c079f8dc26c"),
                            Name = "Tom",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("a74d95b8-22e4-4779-a1ee-962b8f702f0c"),
                            Name = "Misha",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        },
                        new
                        {
                            Id = new Guid("cafe5b9f-1c49-4e12-af1e-29ccd312b506"),
                            Name = "Tezar",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 0
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
